# Generated by Django 5.1.1 on 2024-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="page", options={"ordering": ["title"]},),
        migrations.AddField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("index", "Index"),
                    ("about", "About"),
                    ("booking", "Booking"),
                    ("contact", "Contact"),
                    ("menu", "Menu"),
                    ("service", "Service"),
                    ("team", "Team"),
                    ("testimonial", "Testimonial"),
                ],
                default="index",
                max_length=255,
                unique=True,
            ),
        ),
    ]
