# Generated by Django 5.1.1 on 2024-09-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0002_alter_page_options_page_page_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="page", name="created_at",),
        migrations.RemoveField(model_name="page", name="image",),
        migrations.RemoveField(model_name="page", name="slug",),
        migrations.RemoveField(model_name="page", name="updated_at",),
    ]
