# Generated by Django 5.1.1 on 2024-09-18 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_management",
            "0003_remove_page_created_at_remove_page_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
        migrations.AddField(
            model_name="page",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
